spring:
  application:
    name: PageEventLogger


---
spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/yh_db
      username: root
      password: 0000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc://localhost:3306/yh_mysql

