spring:
  application:
    name: PageEventLogger


---
spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://root:0000@localhost:27017/yh_db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/yh_mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
